FROM openjdk:8

ENV APPDYNAMICS_CONTROLLER_HOST_NAME=your-account-name.saas.appdynamics.com
ENV APPDYNAMICS_CONTROLLER_PORT=443
ENV APPDYNAMICS_CONTROLLER_SSL_ENABLED=true

ENV APPDYNAMICS_AGENT_ACCOUNT_NAME=your-account-name

ENV APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=your-access-key

ENV APPDYNAMICS_AGENT_APPLICATION_NAME=your-application-name

ENV APPDYNAMICS_AGENT_TIER_NAME=your-application-tier-name

ENV APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME=true

ENV APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX=your-node-name-prefix


RUN apt-get update && \
    apt-get install build-essential maven default-jdk cowsay netcat -y && \
    update-alternatives --config javac

RUN mkdir -p /opt/appdynamics
COPY appagent /opt/appdynamics/appagent
WORKDIR /app
COPY target .

ENV JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/appagent/javaagent.jar

CMD ["java", "-jar", "/app/vulnado-0.0.1-SNAPSHOT.jar"]
